# Generated by Django 5.2.2 on 2025-06-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('score', models.IntegerField(verbose_name='Calificación')),
                ('votes', models.IntegerField(verbose_name='Votos Totales')),
                ('finalScore', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Calificación Final')),
            ],
            options={
                'verbose_name': 'Traducción',
                'verbose_name_plural': 'Traducciones',
                'ordering': ['name'],
            },
        ),
    ]
