# Generated by Django 5.2.2 on 2025-07-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("benchmarking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BenchmarkResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_text", models.TextField()),
                ("chatgpt_response", models.TextField()),
                ("deepseek_response", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("metrics", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "benchmark_results",
            },
        ),
        migrations.DeleteModel(
            name="Traduction",
        ),
    ]
